# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8F5oK3NUEwatV-LdlAzlCwuciyEqszS
"""

# Punto 2D

# Camilo Villa Tamayo
# Miguel Angel Sarmiento Aguiar
# Marlon Perez Rios

import math

class Punto2D:

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def get_x(self):
        return self.x

    def get_y(self):
    		return self.y

    def radio_polar(self):
        return math.sqrt((self.x**2) + (self.y**2))

    def angulo_polar(self):
        return math.atan2(self.y, self.x)

    def dist_euclidiana(self, a, b):
    		return math.sqrt(((a - self.x)**2) + ((b - self.y)**2))

p1 = Punto2D(5, 5)
print("Punto: (", p1.x, ",", p1.y, ")")
print("Radio Polar:", p1.radio_polar())
print("Angulo Polar (Radianes):", p1.angulo_polar())
print("Angulo Polar (Grados):",  math.degrees(p1.angulo_polar()))
print("Distancia Euclidiana:",  p1.dist_euclidiana(5, 4))

# Fecha

# Camilo Villa Tamayo
# Miguel Angel Sarmiento Aguiar
# Marlon Perez Rios

class Fecha:

    def __init__(self, dia, mes, año):
        self.dia = dia
        self.mes = mes
        self.año = año

    def get_dia(self):
        return self.dia

    def get_mes(self):
    		return self.mes
    
    def get_año(self):
    		return self.año
    
date1 = Fecha(2, 4, 2017)
date2 = Fecha(2, 4, 2017)

print("Fecha 1:", str(date1.get_dia()) + "/" + str(date1.get_mes()) + "/" + str(date1.get_año()))
print("Fecha 2:", str(date2.get_dia()) + "/" + str(date2.get_mes()) + "/" + str(date2.get_año()))

if date1.get_año() == date2.get_año():
  
  if date1.get_mes() == date2.get_mes():
    
    if date1.get_dia() == date2.get_dia():

      print("La fecha " + str(date1.get_dia()) + " de " + str(date1.get_mes()) + " de " + str(date1.get_año()) + " es igual a " + str(date2.get_dia()) + " de " + str(date2.get_mes()) + " de " + str(date2.get_año()))

    elif date1.get_dia() < date2.get_dia():

      print("La fecha " + str(date1.get_dia()) + " de " + str(date1.get_mes()) + " de " + str(date1.get_año()) + " está antes de " + str(date2.get_dia()) + " de " + str(date2.get_mes()) + " de " + str(date2.get_año()))

    else:

      print("La fecha " + str(date1.get_dia()) + " de " + str(date1.get_mes()) + " de " + str(date1.get_año()) + " está después de " + str(date2.get_dia()) + " de " + str(date2.get_mes()) + " de " + str(date2.get_año()))
  
  elif date1.get_mes() < date2.get_mes():

    print("La fecha " + str(date1.get_dia()) + " de " + str(date1.get_mes()) + " de " + str(date1.get_año()) + " está antes de " + str(date2.get_dia()) + " de " + str(date2.get_mes()) + " de " + str(date2.get_año()))

  else:

    print("La fecha " + str(date1.get_dia()) + " de " + str(date1.get_mes()) + " de " + str(date1.get_año()) + " está después de " + str(date2.get_dia()) + " de " + str(date2.get_mes()) + " de " + str(date2.get_año()))

elif date1.get_año() < date2.get_año():

  print("La fecha " + str(date1.get_dia()) + " de " + str(date1.get_mes()) + " de " + str(date1.get_año()) + " está antes de " + str(date2.get_dia()) + " de " + str(date2.get_mes()) + " de " + str(date2.get_año()))

else:

  print("La fecha " + str(date1.get_dia()) + " de " + str(date1.get_mes()) + " de " + str(date1.get_año()) + " está despues de " + str(date2.get_dia()) + " de " + str(date2.get_mes()) + " de " + str(date2.get_año()))
