# -*- coding: utf-8 -*-
"""Taller2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pV1OOfSIpvS4kN31RWDsDmyM01KBpAj5
"""

#Camilo Villa Tamayo
# Miguel Angel Sarmiento
# Marlon Perez
# PUNTO 1
def gcdEuclidiana(p,q):
    
    if q == 0:
        return p
    
    return gcdEuclidiana(q, p%q)

p = int(input("Ingrese el primer número: "))
q = int(input("Ingrese el segundo número: "))
 
print("El MCD entre ", p, " y ", q, " es ", gcdEuclidiana(p,q))

# PUNTO 2
def Suma_grupo1(nums, target):
  return Suma_grupo(0, nums, target)

def Suma_grupo(start, nums, target):
  if start >= len(nums):
    return target == 0
  else:
    return (Suma_grupo(start+1, nums, target-nums[start]) or Suma_grupo(start+1, nums, target))

print(Suma_grupo1([2, 4, 8],14))