# -*- coding: utf-8 -*-
"""Taller3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dhnnwxjUzDu4bVYe6mr1hQzdMSKqQxgF
"""

# Punto 1

# Camilo Villa Tamayo
# Miguel Angel Sarmiento Aguiar
# Marlon Perez Rios

def hanoi1(topN):
  hanoi(topN, "Torre 1", "Torre 2", "Torre 3")

def hanoi(topN, a, b, c):
  if topN == 1:
    print("Disco 1 desde " + a + " hasta " + c)
  else:
    hanoi(topN - 1, a, c, b)
    print("Disco " + str(topN) + " desde " + a + " hasta " + c)
    hanoi(topN - 1, b, a, c)

hanoi1(3)

# Punto 2

# Camilo Villa Tamayo
# Miguel Angel Sarmiento Aguiar
# Marlon Perez Rios

def permutations1(stri):
  permutations("", stri)



def permutations(base, stri):
  n = len(stri)
  if n == 0:
    print(base)
  else:
    for i in range(n):
      permutations(base + stri[i] , stri[0:i] + stri[i+1:n])

permutations1("abc")